dist: bionic
language: cpp
sudo: required
services:
  - docker

env: SH="docker exec -t container bash -c"

before_install:
  - docker run -d --name container -v $(pwd):/travis -w /travis tjysdsg/tanlang:latest tail -f /dev/null
  - docker ps

install:
  - $SH "./scripts/install-dep.sh"

script:
  - $SH "./scripts/compile-and-test.sh"
