dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 ./compile-and-test.sh

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
