name: CI

on:
  push:
    branches:
      - master

jobs:
  CI_master:
    strategy:
      matrix:
        container: ["tjysdsg/tanlang:latest"]

    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout
        run: git clone https://github.com/tjysdsg/tan --recursive
      - name: compile and test
        run: cd tan; ./scripts/compile-and-test.sh
