name: CI

on:
  push:
    branches:
      - master

jobs:
  CI_master:
    strategy:
      matrix:
        container: ["tjysdsg/tanlang:latest"]

    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.container }}

    steps:
      - name: checkout
        run: git clone https://github.com/tjysdsg/tan --recursive
      - name: compile tanc
        run: cd tan; ./scripts/compile.sh tanc
      - uses: actions/upload-artifact@v1
        with:
          name: bin
          path: tan/bin
      - name: compile all
        run: cd tan; ./scripts/compile.sh all
      - name: compile runtime
        run: cd tan; ./scripts/compile.sh runtime
      - name: test
        run: cd tan; ./scripts/test.sh
