name: CI

on:
  push:
    branches:
      - master

jobs:
  CI_master:
    strategy:
      matrix:
        container: ["tjysdsg/tanlang:latest"]

    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.container }}

    steps:
      - name: checkout
        run: git clone https://github.com/tjysdsg/tan --recursive
      - name: compile all and test all
        run: cd tan; bash scripts/compile.sh
      - name: upload coverage results
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: wget https://codecov.io/bash -O codecov.sh; bash codecov.sh
