name: Continuous Build

on:
  push:
    branches:
      - master

jobs:
  CI_master:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: compile and test
        run: ./scripts/install-dep.sh; ./scripts/compile-and-test.sh
