name: Continuous Build

on: 
  push:
    branches:
    - master
    - parser

jobs:
  CI_master:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: compile and test
      run: ./compile-and-test.sh

  CI_parser:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: compile and test
      run: ./compile-and-test.sh
